In [1]:
from uuid import uuid4
import os
import pandas as pd
from databricks.sdk import WorkspaceClient

from ag_vision.drone.ingest import DroneDataIngest

os.environ.pop('DATABRICKS_HOST', None)
os.environ.pop('DATABRICKS_TOKEN', None)

w = WorkspaceClient(profile='agpile') # set your profile

In [2]:
w.config.host

'https://dbc-0f3d94f2-e27b.cloud.databricks.com'

In [3]:
# Change the following to the location where the local data is stored.
parent_folder_path = '/Users/danielwilliams/Documents/Field Data/drone_upload_test'
raw_image_dir = f'{parent_folder_path}/raw_flight_data/'
files = os.listdir(raw_image_dir)
files = [raw_image_dir + x for x in files]
files

['/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144351_0235_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144459_0269_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144457_0268_MS_RE.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_202411301311_002_TNAU-VBN-30112024-20_PPKRAW.bin',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144453_0266_MS_NIR.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144459_0269_MS_G.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144453_0266_D.JPG',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144449_0264_MS_RE.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144451_0265_D.JPG',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144505_0272_MS_RE.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144439_0259_D.JPG',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144443_0261_MS_NIR.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144509_0274_MS_G.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144507_0273_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144441_0260_MS_G.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144505_0272_MS_NIR.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144441_0260_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144451_0265_MS_NIR.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144507_0273_MS_G.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144451_0265_MS_RE.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144445_0262_D.JPG',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144449_0264_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144441_0260_MS_NIR.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_202411301311_002_TNAU-VBN-30112024-20_PPKOBS.obs',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144447_0263_MS_G.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144501_0270_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144447_0263_MS_RE.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144501_0270_MS_G.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144447_0263_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144449_0264_MS_G.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144447_0263_D.JPG',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144507_0273_MS_NIR.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144509_0274_MS_RE.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144455_0267_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144445_0262_MS_RE.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144457_0268_MS_G.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144457_0268_D.JPG',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144459_0269_MS_RE.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144457_0268_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144505_0272_D.JPG',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144457_0268_MS_NIR.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144455_0267_MS_G.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144439_0259_MS_NIR.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144503_0271_MS_NIR.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144443_0261_MS_RE.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144445_0262_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144453_0266_MS_RE.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144503_0271_MS_G.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144437_0258_D.JPG',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144503_0271_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144445_0262_MS_NIR.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_202411301311_002_TNAU-VBN-30112024-20_PPKNAV.nav',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144445_0262_MS_G.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144455_0267_D.JPG',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144437_0258_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_202411301311_002_TNAU-VBN-30112024-20_Timestamp.MRK',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144413_0246_D.JPG',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144437_0258_MS_NIR.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144453_0266_MS_G.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144441_0260_MS_RE.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144453_0266_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144459_0269_D.JPG',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144501_0270_MS_RE.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144441_0260_D.JPG',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144449_0264_D.JPG',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144439_0259_MS_RE.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144451_0265_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144455_0267_MS_RE.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144501_0270_MS_NIR.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144505_0272_MS_G.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144455_0267_MS_NIR.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144439_0259_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144443_0261_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144503_0271_D.JPG',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144443_0261_MS_G.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144501_0270_D.JPG',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144439_0259_MS_G.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144505_0272_MS_R.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144449_0264_MS_NIR.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144503_0271_MS_RE.TIF',
 '/Users/danielwilliams/Documents/Field Data/drone_upload_test/raw_flight_data/DJI_20241124144447_0263_MS_NIR.TIF']

In [4]:
flight_metadata = {
    "id": str(uuid4()),
    "name": "corn_health_assessment_flight",  # this will be the mission name in the folder path
    "task": "drone_phenotyping",
    "location": {
        "site": "TNAU-Coimbatore".lower(),  # Try to keep these standard ORG-Site EX CIAT-Cali, or CIAT-Arusha....
        "field": "West_Field_03".lower(),
        # what is the name of the field that the trial was run on? The field and location can be the same name if there is no difference.
        "location": "Section_B".lower()
        # The location corresponds to a specific field book. If data is in EBS match the location name.
    },
    "trialProperties": {
        "name": "BETS"  # What is the name of the trial, a trial usually has multiple locations.
    },
    "drone_acquisition_properties": {
        'date': '11/25/2024',
        'drone_make': "DJI",
        'drone_model': "Phantom Mavic 4 Enterprise",
        'camera_make': "Sony",
        'camera_model': "UCM-R",
        'groundControlPoints': True,
        'reflectancePanels': True,
        'reflectancePanelType': 'Micasense',
        'flightHeight': 90.0,
        'horizontalOverlapPercentage': 75.0,
        'verticalOverlapPercentage': 75.0,
        'gpsQuality': "RTK",
        'multispecChannels': ["Red", "Green", "Blue", "NIR"]
    },
    "agronomic_properties": {
        "crop_type": "corn",  # Required
        "growth_stage": "VT",  # optional
        "soil_color": None,
        "weed_pressure": None,
        "irrigation_level": None,
        "tillage_type": None,
        "fertilizer_level": None
    }
}

In [5]:
# This points to the aps1-prod-tnau-fg workspace _YOU SHOULD NOT NEED TO CHANGE THIS.
# TNAU
#workspace_bucket = '/Volumes/aps1_prod_tnau_fg_catalog_1336582592012881/tier1_raw/data'
# AgPile
workspace_bucket = '/Volumes/ue1_prod_catalog_119738067017277/tier1_raw/data'

ingest = DroneDataIngest(platform='local',  # DONT CHANGE THIS
                         cloud_bucket=workspace_bucket, # Set this to the bucket you want to save the data to.
                         cloud_client=w, # should not need to change.
                         flight_date='11/25/2024',
                         plot_boundary_key=f"{parent_folder_path}/plot_boundary.geojson",
                         gcp_key=f"{parent_folder_path}/gcp_details.geojson",
                         orthomosaic_key=f"{parent_folder_path}/30112024_ORTHO.tif",
                         dem_key=f"{parent_folder_path}/30112024_DSM.tif",
                         flight_metadata_key=f"{parent_folder_path}/flight_details.json")  # If this does not exist then this just tells the code were to save it so it can be uploaded.

In [6]:
ingest.load_metadata_from_dict(metadata_dict=flight_metadata)

# season is needed to generate the mission dir, This has lots of Validation and will throw assert errors.
ingest.add_season_code_to_metadata(year=2025,
                                   country='IND',
                                   crop='maize',
                                   time_of_year='spring')

# This is the main dir where all the data will be stored.
ingest.generate_drone_mission_dir_path()

In [7]:
# This saves the metadata locally do it can be uploaded.
ingest.save_flight_metadata_to_json_local()

In [25]:
# This will be a list of all the raw files from the flight eg: nav, bin, tif, and jpg files.
ingest.generate_raw_ingest_df(file_list=files)

In [28]:
ingest.raw_ingest_df['img_ext'].unique()

array(['.TIF', '.bin', '.JPG', '.obs', '.nav', '.MRK'], dtype=object)

In [31]:
# Adding the camera col so the RGB and flight data will go into the RGB folder, and the MS and flight data will go into the multi-spec folder.

def determine_camera_type(f_name):
    if "_MS_" in f_name:
        return 'multi-spec'
    elif ".JPG" in f_name:
        return 'rgb'
    else:
        return 'flight_data'

ingest.raw_ingest_df['camera'] = ingest.raw_ingest_df['file_name'].apply(determine_camera_type)
flight_data = ingest.raw_ingest_df[ingest.raw_ingest_df['camera'] == 'flight_data']
flight_data.head()

,src_path,file_name,img_ext,file_type,camera
3,/Users/danielwilliams/Documents/Field Data/dro...,DJI_202411301311_002_TNAU-VBN-30112024-20_PPKR...,.bin,None,flight_data
23,/Users/danielwilliams/Documents/Field Data/dro...,DJI_202411301311_002_TNAU-VBN-30112024-20_PPKO...,.obs,None,flight_data
51,/Users/danielwilliams/Documents/Field Data/dro...,DJI_202411301311_002_TNAU-VBN-30112024-20_PPKN...,.nav,None,flight_data
55,/Users/danielwilliams/Documents/Field Data/dro...,DJI_202411301311_002_TNAU-VBN-30112024-20_Time...,.MRK,None,flight_data

In [32]:
f_ingest_df_list = []

# The flight data needs to be saved with both camera data sets.
for idx, df in ingest.raw_ingest_df.groupby('camera'):
    if idx in ['rgb', 'multi-spec']:
        out_df = pd.concat([df, flight_data])
        out_df['camera'] = idx
        f_ingest_df_list.append(out_df)

f_ingest_df = pd.concat(f_ingest_df_list)

In [33]:
ingest.raw_ingest_df = f_ingest_df

In [34]:
flight_data.head()

,src_path,file_name,img_ext,file_type,camera
3,/Users/danielwilliams/Documents/Field Data/dro...,DJI_202411301311_002_TNAU-VBN-30112024-20_PPKR...,.bin,None,flight_data
23,/Users/danielwilliams/Documents/Field Data/dro...,DJI_202411301311_002_TNAU-VBN-30112024-20_PPKO...,.obs,None,flight_data
51,/Users/danielwilliams/Documents/Field Data/dro...,DJI_202411301311_002_TNAU-VBN-30112024-20_PPKN...,.nav,None,flight_data
55,/Users/danielwilliams/Documents/Field Data/dro...,DJI_202411301311_002_TNAU-VBN-30112024-20_Time...,.MRK,None,flight_data

In [35]:
# generates the new path names where to save it in databricks
ingest.generate_raw_image_dst_path_name()

In [36]:
# Upload the metadata to databricks
ingest.upload_metadata_to_db()

Uploading: 100%|██████████| 1.65k/1.65k [00:01<00:00, 1.59kB/s]

In [37]:
# uploads the plot boundaries to databricks
ingest.upload_plot_boundary_to_db()

Saving to /Volumes/ue1_prod_catalog_119738067017277/tier1_raw/data/tnau-coimbatore/bets/2025:ind:maize:spring/west_field_03/section_b/drone/corn_health_assessment_flight/field_data/plot_boundary.geojson

Uploading: 100%|██████████| 190k/190k [00:00<00:00, 292kB/s]

In [38]:
# Uploads the ground control points to databricks
ingest.upload_gcp_to_db()

Saving to /Volumes/ue1_prod_catalog_119738067017277/tier1_raw/data/tnau-coimbatore/bets/2025:ind:maize:spring/west_field_03/section_b/drone/corn_health_assessment_flight/field_data/ground_control_points.geojson

Uploading: 100%|██████████| 1.28k/1.28k [00:01<00:00, 1.20kB/s]

In [39]:
# uploads all the raw flight data to databricks
ingest.upload_raw_flight_data_to_db()

0it [00:00, ?it/s]
Uploading:   0%|          | 0.00/10.1M [00:00<?, ?B/s]
Uploading:   2%|▏         | 160k/9.62M [00:00<00:06, 1.61MB/s]
Uploading:   3%|▎         | 320k/9.62M [00:00<00:09, 1.04MB/s]
Uploading:   7%|▋         | 704k/9.62M [00:00<00:04, 1.96MB/s]
Uploading:  13%|█▎        | 1.28M/9.62M [00:00<00:02, 3.26MB/s]
Uploading:  18%|█▊        | 1.69M/9.62M [00:00<00:02, 3.41MB/s]
Uploading:  26%|██▌       | 2.52M/9.62M [00:00<00:01, 4.96MB/s]
Uploading:  33%|███▎      | 3.20M/9.62M [00:00<00:01, 4.74MB/s]
Uploading:  40%|███▉      | 3.83M/9.62M [00:01<00:01, 5.03MB/s]
Uploading:  45%|████▌     | 4.34M/9.62M [00:01<00:01, 5.04MB/s]
Uploading:  50%|█████     | 4.84M/9.62M [00:01<00:01, 3.80MB/s]
Uploading:  55%|█████▍    | 5.27M/9.62M [00:01<00:01, 3.84MB/s]
Uploading:  59%|█████▉    | 5.67M/9.62M [00:01<00:01, 3.47MB/s]
Uploading:  63%|██████▎   | 6.03M/9.62M [00:01<00:01, 3.49MB/s]
Uploading:  66%|██████▋   | 6.39M/9.62M [00:01<00:01, 3.00MB/s]
Uploading:  70%|██████▉   | 6.70M/9.62M [00:04<00:05, 515kB/s]
Uploading:  72%|███████▏  | 6.94M/9.62M [00:04<00:05, 530kB/s]
Uploading:  74%|███████▍  | 7.11M/9.62M [00:05<00:05, 487kB/s]
Uploading:  75%|███████▌  | 7.25M/9.62M [00:05<00:05, 464kB/s]
Uploading:  76%|███████▋  | 7.36M/9.62M [00:05<00:05, 447kB/s]
Uploading:  77%|███████▋  | 7.45M/9.62M [00:05<00:04, 456kB/s]
Uploading:  78%|███████▊  | 7.53M/9.62M [00:06<00:04, 473kB/s]
Uploading:  79%|███████▉  | 7.61M/9.62M [00:06<00:04, 476kB/s]
Uploading:  80%|███████▉  | 7.67M/9.62M [00:06<00:04, 500kB/s]
Uploading:  80%|████████  | 7.73M/9.62M [00:06<00:03, 517kB/s]
Uploading:  81%|████████  | 7.80M/9.62M [00:06<00:04, 453kB/s]
Uploading:  82%|████████▏ | 7.88M/9.62M [00:06<00:03, 515kB/s]
Uploading:  83%|████████▎ | 7.94M/9.62M [00:06<00:03, 542kB/s]
Uploading:  83%|████████▎ | 8.00M/9.62M [00:07<00:03, 556kB/s]
Uploading:  84%|████████▍ | 8.08M/9.62M [00:07<00:03, 515kB/s]
Uploading:  85%|████████▍ | 8.16M/9.62M [00:07<00:02, 579kB/s]
Uploading:  86%|████████▌ | 8.25M/9.62M [00:07<00:02, 614kB/s]
Uploading:  87%|████████▋ | 8.33M/9.62M [00:07<00:02, 657kB/s]
Uploading:  88%|████████▊ | 8.42M/9.62M [00:07<00:01, 650kB/s]
Uploading:  89%|████████▊ | 8.52M/9.62M [00:07<00:01, 699kB/s]
Uploading:  89%|████████▉ | 8.61M/9.62M [00:07<00:01, 742kB/s]
Uploading:  90%|█████████ | 8.69M/9.62M [00:08<00:01, 762kB/s]
Uploading:  91%|█████████▏| 8.78M/9.62M [00:08<00:01, 711kB/s]
Uploading:  92%|█████████▏| 8.86M/9.62M [00:08<00:01, 723kB/s]
Uploading:  93%|█████████▎| 8.97M/9.62M [00:08<00:00, 820kB/s]
Uploading:  94%|█████████▍| 9.08M/9.62M [00:08<00:00, 886kB/s]
Uploading:  95%|█████████▌| 9.17M/9.62M [00:08<00:00, 895kB/s]
Uploading:  96%|█████████▋| 9.27M/9.62M [00:08<00:00, 757kB/s]
Uploading:  98%|█████████▊| 9.39M/9.62M [00:08<00:00, 861kB/s]
Uploading:  99%|█████████▊| 9.48M/9.62M [00:09<00:00, 841kB/s]
Uploading: 100%|██████████| 9.62M/9.62M [00:09<00:00, 1.05MB/s][A
1it [00:09,  9.61s/it]
Uploading:   0%|          | 0.00/10.1M [00:00<?, ?B/s]
Uploading:   2%|▏         | 224k/9.62M [00:00<00:04, 2.06MB/s]
Uploading:   4%|▍         | 432k/9.62M [00:00<00:07, 1.38MB/s]
Uploading:   6%|▌         | 592k/9.62M [00:00<00:07, 1.31MB/s]
Uploading:   7%|▋         | 736k/9.62M [00:00<00:07, 1.32MB/s]
Uploading:   9%|▉         | 880k/9.62M [00:00<00:07, 1.31MB/s]
Uploading:  10%|█         | 1.00M/9.62M [00:00<00:07, 1.15MB/s]
Uploading:  12%|█▏        | 1.19M/9.62M [00:00<00:06, 1.30MB/s]
Uploading:  14%|█▍        | 1.36M/9.62M [00:01<00:06, 1.37MB/s]
Uploading:  16%|█▌        | 1.52M/9.62M [00:01<00:06, 1.40MB/s]
Uploading:  18%|█▊        | 1.70M/9.62M [00:01<00:05, 1.54MB/s]
Uploading:  19%|█▉        | 1.88M/9.62M [00:01<00:05, 1.56MB/s]
Uploading:  21%|██▏       | 2.05M/9.62M [00:01<00:04, 1.60MB/s]
Uploading:  23%|██▎       | 2.25M/9.62M [00:01<00:04, 1.72MB/s]
Uploading:  25%|██▌       | 2.45M/9.62M [00:01<00:04, 1.83MB/s]
Uploading:  27%|██▋       | 2.64M/9.62M [00:01<00:04, 1.78MB/s]
Uploading:  30%|██▉       | 2.86M/9.62M [00:01<00:03, 1.92MB/s]
Uploading:  32%|███▏      | 3.05M/9.62M [00:02<00:03, 1.92MB/s]
Uploading:  34%|███▍      | 3.30M/9.62M [00:02<00:03, 2.07MB/s]
Uploading:  37%|███▋      | 3.55M/9.62M [00:02<00:02, 2.19MB/s]
Uploading:  39%|███▉      | 3.78M/9.62M [00:02<00:02, 2.26MB/s]
Uploading:  42%|████▏     | 4.05M/9.62M [00:02<00:02, 2.39MB/s]
Uploading:  45%|████▌     | 4.34M/9.62M [00:02<00:02, 2.51MB/s]
Uploading:  48%|████▊     | 4.62M/9.62M [00:02<00:02, 2.47MB/s]
Uploading:  51%|█████▏    | 4.94M/9.62M [00:02<00:01, 2.63MB/s]
Uploading:  55%|█████▍    | 5.27M/9.62M [00:02<00:01, 2.74MB/s]
Uploading:  58%|█████▊    | 5.58M/9.62M [00:03<00:01, 2.84MB/s]
Uploading:  61%|██████▏   | 5.91M/9.62M [00:03<00:01, 3.00MB/s]
Uploading:  64%|██████▍   | 6.20M/9.62M [00:03<00:01, 3.00MB/s]
Uploading:  69%|██████▊   | 6.59M/9.62M [00:03<00:01, 3.17MB/s]
Uploading:  72%|███████▏  | 6.95M/9.62M [00:03<00:00, 3.26MB/s]
Uploading:  76%|███████▌  | 7.30M/9.62M [00:03<00:00, 3.33MB/s]
Uploading:  80%|███████▉  | 7.66M/9.62M [00:03<00:00, 3.38MB/s]
Uploading:  84%|████████▎ | 8.05M/9.62M [00:03<00:00, 3.52MB/s]
Uploading:  87%|████████▋ | 8.39M/9.62M [00:04<00:00, 1.63MB/s]
Uploading:  91%|█████████▏| 8.78M/9.62M [00:04<00:00, 2.01MB/s]
Uploading:  94%|█████████▍| 9.08M/9.62M [00:04<00:00, 2.06MB/s]
Uploading:  97%|█████████▋| 9.36M/9.62M [00:04<00:00, 2.11MB/s]
Uploading: 100%|██████████| 9.62M/9.62M [00:05<00:00, 1.95MB/s]
2it [00:14,  7.01s/it]
Uploading:   0%|          | 0.00/10.1M [00:00<?, ?B/s]
Uploading:   5%|▌         | 528k/9.62M [00:00<00:01, 5.20MB/s]
Uploading:  11%|█         | 1.02M/9.62M [00:00<00:02, 3.24MB/s]
Uploading:  14%|█▍        | 1.38M/9.62M [00:00<00:03, 2.75MB/s]
Uploading:  17%|█▋        | 1.67M/9.62M [00:00<00:03, 2.62MB/s]
Uploading:  20%|██        | 1.94M/9.62M [00:00<00:03, 2.64MB/s]
Uploading:  23%|██▎       | 2.20M/9.62M [00:00<00:03, 2.49MB/s]
Uploading:  25%|██▌       | 2.45M/9.62M [00:00<00:03, 2.38MB/s]
Uploading:  28%|██▊       | 2.69M/9.62M [00:01<00:03, 2.35MB/s]
Uploading:  30%|███       | 2.92M/9.62M [00:01<00:03, 2.31MB/s]
Uploading:  33%|███▎      | 3.16M/9.62M [00:01<00:03, 2.25MB/s]
Uploading:  35%|███▌      | 3.41M/9.62M [00:01<00:02, 2.23MB/s]
Uploading:  38%|███▊      | 3.62M/9.62M [00:01<00:03, 1.58MB/s]
Uploading:  40%|████      | 3.89M/9.62M [00:01<00:03, 1.83MB/s]
Uploading:  43%|████▎     | 4.09M/9.62M [00:01<00:03, 1.88MB/s]
Uploading:  45%|████▍     | 4.30M/9.62M [00:01<00:02, 1.91MB/s]
Uploading:  47%|████▋     | 4.50M/9.62M [00:02<00:02, 1.83MB/s]
Uploading:  49%|████▉     | 4.70M/9.62M [00:02<00:02, 1.87MB/s]
Uploading:  51%|█████     | 4.89M/9.62M [00:02<00:02, 1.82MB/s]
Uploading:  53%|█████▎    | 5.11M/9.62M [00:02<00:02, 1.93MB/s]
Uploading:  55%|█████▌    | 5.31M/9.62M [00:02<00:02, 1.95MB/s]
Uploading:  58%|█████▊    | 5.56M/9.62M [00:02<00:02, 1.98MB/s]
Uploading:  60%|█████▉    | 5.77M/9.62M [00:02<00:02, 1.99MB/s]
Uploading:  62%|██████▏   | 5.97M/9.62M [00:02<00:02, 1.89MB/s]
Uploading:  64%|██████▍   | 6.16M/9.62M [00:03<00:01, 1.91MB/s]
Uploading:  66%|██████▌   | 6.36M/9.62M [00:03<00:01, 1.94MB/s]
Uploading:  68%|██████▊   | 6.55M/9.62M [00:03<00:01, 1.93MB/s]
Uploading:  70%|███████   | 6.77M/9.62M [00:03<00:01, 1.99MB/s]
Uploading:  72%|███████▏  | 6.97M/9.62M [00:03<00:01, 2.00MB/s]
Uploading:  75%|███████▍  | 7.17M/9.62M [00:03<00:01, 1.93MB/s]
Uploading:  77%|███████▋  | 7.39M/9.62M [00:03<00:01, 1.97MB/s]
Uploading:  79%|███████▉  | 7.59M/9.62M [00:03<00:01, 1.97MB/s]
Uploading:  81%|████████  | 7.81M/9.62M [00:03<00:00, 1.96MB/s]
Uploading:  83%|████████▎ | 8.02M/9.62M [00:03<00:00, 2.00MB/s]
Uploading:  85%|████████▌ | 8.22M/9.62M [00:05<00:02, 518kB/s]
Uploading:  87%|████████▋ | 8.36M/9.62M [00:05<00:02, 510kB/s]
Uploading:  88%|████████▊ | 8.48M/9.62M [00:05<00:02, 491kB/s]
Uploading:  89%|████████▉ | 8.58M/9.62M [00:05<00:02, 490kB/s]
Uploading:  90%|████████▉ | 8.66M/9.62M [00:06<00:02, 484kB/s]
Uploading:  91%|█████████ | 8.73M/9.62M [00:06<00:01, 503kB/s]
Uploading:  92%|█████████▏| 8.81M/9.62M [00:06<00:01, 515kB/s]
Uploading:  92%|█████████▏| 8.88M/9.62M [00:06<00:01, 538kB/s]
Uploading:  93%|█████████▎| 8.95M/9.62M [00:06<00:01, 544kB/s]
Uploading:  94%|█████████▎| 9.02M/9.62M [00:06<00:01, 565kB/s]
Uploading:  95%|█████████▍| 9.09M/9.62M [00:06<00:00, 570kB/s]
Uploading:  95%|█████████▌| 9.16M/9.62M [00:07<00:00, 580kB/s]
Uploading:  96%|█████████▋| 9.27M/9.62M [00:07<00:00, 668kB/s]
Uploading:  97%|█████████▋| 9.34M/9.62M [00:07<00:00, 619kB/s]
Uploading:  98%|█████████▊| 9.42M/9.62M [00:07<00:00, 660kB/s]
Uploading:  99%|█████████▉| 9.50M/9.62M [00:07<00:00, 700kB/s]
Uploading: 100%|██████████| 9.62M/9.62M [00:08<00:00, 1.25MB/s][A
3it [00:22,  7.50s/it]
Uploading:   0%|          | 0.00/10.1M [00:00<?, ?B/s]
Uploading:   2%|▏         | 192k/9.62M [00:00<00:06, 1.62MB/s]
Uploading:   4%|▎         | 352k/9.62M [00:00<00:08, 1.08MB/s]
Uploading:   5%|▍         | 480k/9.62M [00:00<00:09, 1.02MB/s]
Uploading:   6%|▌         | 592k/9.62M [00:00<00:10, 931kB/s]
Uploading:   7%|▋         | 688k/9.62M [00:00<00:10, 856kB/s]
Uploading:   8%|▊         | 784k/9.62M [00:00<00:10, 884kB/s]
Uploading:   9%|▉         | 896k/9.62M [00:00<00:09, 935kB/s]
Uploading:  10%|█         | 0.98M/9.62M [00:01<00:09, 989kB/s]
Uploading:  11%|█▏        | 1.09M/9.62M [00:01<00:09, 987kB/s]
Uploading:  13%|█▎        | 1.20M/9.62M [00:01<00:09, 899kB/s]
Uploading:  13%|█▎        | 1.30M/9.62M [00:01<00:09, 919kB/s]
Uploading:  14%|█▍        | 1.39M/9.62M [00:01<00:09, 926kB/s]
Uploading:  15%|█▌        | 1.48M/9.62M [00:01<00:09, 937kB/s]
Uploading:  17%|█▋        | 1.61M/9.62M [00:01<00:08, 1.03MB/s]
Uploading:  18%|█▊        | 1.72M/9.62M [00:01<00:07, 1.04MB/s]
Uploading:  19%|█▉        | 1.86M/9.62M [00:01<00:07, 1.15MB/s]
Uploading:  21%|██        | 1.98M/9.62M [00:02<00:07, 1.07MB/s]
Uploading:  22%|██▏       | 2.09M/9.62M [00:02<00:08, 982kB/s]
Uploading:  23%|██▎       | 2.22M/9.62M [00:02<00:07, 1.01MB/s]
Uploading:  25%|██▍       | 2.36M/9.62M [00:02<00:06, 1.13MB/s]
Uploading:  26%|██▌       | 2.48M/9.62M [00:02<00:06, 1.16MB/s]
Uploading:  27%|██▋       | 2.62M/9.62M [00:02<00:06, 1.22MB/s]
Uploading:  29%|██▉       | 2.80M/9.62M [00:02<00:05, 1.34MB/s]
Uploading:  31%|███       | 2.94M/9.62M [00:02<00:05, 1.36MB/s]
Uploading:  32%|███▏      | 3.11M/9.62M [00:03<00:05, 1.33MB/s]
Uploading:  34%|███▍      | 3.30M/9.62M [00:03<00:04, 1.43MB/s]
Uploading:  36%|███▌      | 3.47M/9.62M [00:03<00:04, 1.50MB/s]
Uploading:  38%|███▊      | 3.66M/9.62M [00:03<00:03, 1.62MB/s]
Uploading:  40%|████      | 3.86M/9.62M [00:03<00:03, 1.70MB/s]
Uploading:  42%|████▏     | 4.05M/9.62M [00:03<00:03, 1.77MB/s]
Uploading:  44%|████▍     | 4.25M/9.62M [00:03<00:03, 1.84MB/s]
Uploading:  46%|████▋     | 4.45M/9.62M [00:03<00:02, 1.89MB/s]
Uploading:  49%|████▊     | 4.67M/9.62M [00:03<00:02, 1.97MB/s]
Uploading:  51%|█████     | 4.88M/9.62M [00:03<00:02, 1.97MB/s]
Uploading:  53%|█████▎    | 5.14M/9.62M [00:04<00:02, 2.14MB/s]
Uploading:  56%|█████▌    | 5.41M/9.62M [00:04<00:02, 2.18MB/s]
Uploading:  59%|█████▉    | 5.69M/9.62M [00:04<00:01, 2.26MB/s]
Uploading:  62%|██████▏   | 5.95M/9.62M [00:04<00:01, 2.25MB/s]
Uploading:  65%|██████▍   | 6.23M/9.62M [00:04<00:01, 2.28MB/s]
Uploading:  67%|██████▋   | 6.45M/9.62M [00:04<00:01, 2.23MB/s]
Uploading:  69%|██████▉   | 6.67M/9.62M [00:04<00:01, 2.12MB/s]
Uploading:  72%|███████▏  | 6.95M/9.62M [00:05<00:01, 1.80MB/s]
Uploading:  76%|███████▌  | 7.27M/9.62M [00:05<00:01, 2.00MB/s]
Uploading:  79%|███████▉  | 7.61M/9.62M [00:05<00:01, 2.10MB/s]
Uploading:  83%|████████▎ | 7.95M/9.62M [00:05<00:00, 1.86MB/s]
Uploading:  85%|████████▌ | 8.22M/9.62M [00:05<00:00, 2.00MB/s]
Uploading:  89%|████████▉ | 8.56M/9.62M [00:05<00:00, 2.07MB/s]
Uploading:  93%|█████████▎| 8.92M/9.62M [00:05<00:00, 2.39MB/s]
Uploading:  95%|█████████▌| 9.17M/9.62M [00:06<00:00, 2.39MB/s]
Uploading: 100%|██████████| 9.62M/9.62M [00:06<00:00, 1.46MB/s]
4it [00:29,  7.26s/it]
Uploading:   0%|          | 0.00/10.1M [00:00<?, ?B/s]
Uploading:  10%|█         | 0.98M/9.62M [00:00<00:01, 6.22MB/s]
Uploading:  16%|█▋        | 1.58M/9.62M [00:00<00:01, 5.70MB/s]
Uploading:  22%|██▏       | 2.12M/9.62M [00:00<00:02, 3.60MB/s]
Uploading:  26%|██▌       | 2.52M/9.62M [00:00<00:02, 3.36MB/s]
Uploading:  30%|██▉       | 2.86M/9.62M [00:00<00:02, 3.25MB/s]
Uploading:  33%|███▎      | 3.19M/9.62M [00:00<00:02, 2.76MB/s]
Uploading:  37%|███▋      | 3.59M/9.62M [00:01<00:02, 3.07MB/s]
Uploading:  41%|████      | 3.91M/9.62M [00:01<00:02, 2.75MB/s]
Uploading:  45%|████▍     | 4.30M/9.62M [00:01<00:02, 2.59MB/s]
Uploading:  49%|████▊     | 4.67M/9.62M [00:01<00:01, 2.70MB/s]
Uploading:  51%|█████▏    | 4.95M/9.62M [00:01<00:01, 2.60MB/s]
Uploading:  56%|█████▌    | 5.38M/9.62M [00:01<00:01, 2.67MB/s]
Uploading:  60%|██████    | 5.80M/9.62M [00:01<00:01, 3.01MB/s]
Uploading:  64%|██████▎   | 6.11M/9.62M [00:02<00:01, 2.89MB/s]
Uploading:  68%|██████▊   | 6.58M/9.62M [00:02<00:00, 3.33MB/s]
Uploading:  72%|███████▏  | 6.92M/9.62M [00:02<00:01, 1.79MB/s]
Uploading:  76%|███████▌  | 7.28M/9.62M [00:03<00:01, 1.25MB/s]
Uploading:  82%|████████▏ | 7.89M/9.62M [00:03<00:00, 1.86MB/s]
Uploading:  86%|████████▌ | 8.23M/9.62M [00:03<00:00, 2.11MB/s]
Uploading:  89%|████████▉ | 8.56M/9.62M [00:04<00:00, 1.20MB/s]
Uploading:  93%|█████████▎| 8.94M/9.62M [00:04<00:00, 1.48MB/s]
Uploading:  96%|█████████▌| 9.20M/9.62M [00:04<00:00, 1.65MB/s]
Uploading: 100%|██████████| 9.62M/9.62M [00:04<00:00, 2.08MB/s]
5it [00:34,  6.39s/it]
Uploading:   0%|          | 0.00/10.1M [00:00<?, ?B/s]
Uploading:   6%|▌         | 608k/9.62M [00:00<00:01, 5.95MB/s]
Uploading:  12%|█▏        | 1.17M/9.62M [00:00<00:02, 3.15MB/s]
Uploading:  16%|█▌        | 1.55M/9.62M [00:00<00:02, 2.83MB/s]
Uploading:  19%|█▉        | 1.86M/9.62M [00:00<00:03, 2.66MB/s]
Uploading:  22%|██▏       | 2.14M/9.62M [00:00<00:02, 2.67MB/s]
Uploading:  25%|██▌       | 2.41M/9.62M [00:00<00:02, 2.68MB/s]
Uploading:  28%|██▊       | 2.70M/9.62M [00:00<00:02, 2.75MB/s]
Uploading:  31%|███       | 2.98M/9.62M [00:01<00:02, 2.72MB/s]
Uploading:  34%|███▍      | 3.25M/9.62M [00:01<00:05, 1.22MB/s]
Uploading:  37%|███▋      | 3.59M/9.62M [00:02<00:08, 723kB/s]
Uploading:  40%|████      | 3.88M/9.62M [00:02<00:07, 859kB/s]
Uploading:  42%|████▏     | 4.03M/9.62M [00:02<00:06, 941kB/s]
Uploading:  44%|████▎     | 4.19M/9.62M [00:02<00:05, 1.02MB/s]
Uploading:  45%|████▌     | 4.34M/9.62M [00:03<00:05, 1.10MB/s]
Uploading:  47%|████▋     | 4.50M/9.62M [00:03<00:04, 1.19MB/s]
Uploading:  48%|████▊     | 4.66M/9.62M [00:03<00:04, 1.27MB/s]
Uploading:  50%|█████     | 4.81M/9.62M [00:03<00:03, 1.32MB/s]
Uploading:  52%|█████▏    | 4.98M/9.62M [00:03<00:03, 1.39MB/s]
Uploading:  53%|█████▎    | 5.14M/9.62M [00:03<00:03, 1.44MB/s]
Uploading:  55%|█████▌    | 5.30M/9.62M [00:03<00:03, 1.44MB/s]
Uploading:  57%|█████▋    | 5.50M/9.62M [00:03<00:02, 1.58MB/s]
Uploading:  59%|█████▉    | 5.67M/9.62M [00:03<00:02, 1.53MB/s]
Uploading:  61%|██████    | 5.84M/9.62M [00:04<00:02, 1.59MB/s]
Uploading:  63%|██████▎   | 6.02M/9.62M [00:04<00:02, 1.57MB/s]
Uploading:  64%|██████▍   | 6.17M/9.62M [00:04<00:02, 1.53MB/s]
Uploading:  66%|██████▌   | 6.36M/9.62M [00:04<00:02, 1.56MB/s]
Uploading:  68%|██████▊   | 6.55M/9.62M [00:04<00:01, 1.67MB/s]
Uploading:  70%|██████▉   | 6.72M/9.62M [00:04<00:01, 1.68MB/s]
Uploading:  72%|███████▏  | 6.89M/9.62M [00:04<00:01, 1.57MB/s]
Uploading:  73%|███████▎  | 7.06M/9.62M [00:04<00:01, 1.63MB/s]
Uploading:  75%|███████▌  | 7.25M/9.62M [00:04<00:01, 1.70MB/s]
Uploading:  77%|███████▋  | 7.42M/9.62M [00:05<00:01, 1.71MB/s]
Uploading:  79%|███████▉  | 7.59M/9.62M [00:05<00:01, 1.72MB/s]
Uploading:  81%|████████  | 7.78M/9.62M [00:05<00:01, 1.75MB/s]
Uploading:  83%|████████▎ | 7.95M/9.62M [00:05<00:01, 1.73MB/s]
Uploading:  84%|████████▍ | 8.12M/9.62M [00:05<00:00, 1.74MB/s]
Uploading:  86%|████████▌ | 8.30M/9.62M [00:05<00:00, 1.73MB/s]
Uploading:  88%|████████▊ | 8.47M/9.62M [00:05<00:00, 1.68MB/s]
Uploading:  90%|████████▉ | 8.64M/9.62M [00:05<00:00, 1.70MB/s]
Uploading:  92%|█████████▏| 8.81M/9.62M [00:05<00:00, 1.73MB/s]
Uploading:  93%|█████████▎| 8.98M/9.62M [00:05<00:00, 1.73MB/s]
Uploading:  95%|█████████▌| 9.16M/9.62M [00:06<00:00, 1.75MB/s]
Uploading:  97%|█████████▋| 9.33M/9.62M [00:06<00:00, 1.72MB/s]
Uploading: 100%|██████████| 9.62M/9.62M [00:06<00:00, 1.48MB/s]
6it [00:41,  6.54s/it]
Uploading:   0%|          | 0.00/10.1M [00:00<?, ?B/s]
Uploading:   4%|▍         | 416k/9.62M [00:00<00:02, 3.81MB/s]
Uploading:   8%|▊         | 800k/9.62M [00:00<00:03, 2.40MB/s]
Uploading:  11%|█         | 1.05M/9.62M [00:00<00:04, 2.20MB/s]
Uploading:  13%|█▎        | 1.28M/9.62M [00:00<00:03, 2.19MB/s]
Uploading:  16%|█▌        | 1.50M/9.62M [00:00<00:04, 1.99MB/s]
Uploading:  18%|█▊        | 1.70M/9.62M [00:00<00:04, 1.96MB/s]
Uploading:  20%|█▉        | 1.91M/9.62M [00:00<00:04, 1.90MB/s]
Uploading:  22%|██▏       | 2.09M/9.62M [00:01<00:04, 1.78MB/s]
Uploading:  24%|██▎       | 2.27M/9.62M [00:01<00:04, 1.74MB/s]
Uploading:  25%|██▌       | 2.44M/9.62M [00:01<00:04, 1.70MB/s]
Uploading:  27%|██▋       | 2.61M/9.62M [00:01<00:04, 1.69MB/s]
Uploading:  29%|██▉       | 2.83M/9.62M [00:01<00:03, 1.79MB/s]
Uploading:  31%|███       | 3.00M/9.62M [00:01<00:04, 1.65MB/s]
Uploading:  33%|███▎      | 3.19M/9.62M [00:01<00:04, 1.64MB/s]
Uploading:  35%|███▌      | 3.38M/9.62M [00:01<00:03, 1.71MB/s]
Uploading:  37%|███▋      | 3.56M/9.62M [00:02<00:03, 1.66MB/s]
Uploading:  39%|███▉      | 3.77M/9.62M [00:02<00:03, 1.74MB/s]
Uploading:  41%|████      | 3.95M/9.62M [00:02<00:03, 1.68MB/s]
Uploading:  43%|████▎     | 4.17M/9.62M [00:02<00:03, 1.78MB/s]
Uploading:  45%|████▌     | 4.34M/9.62M [00:02<00:03, 1.67MB/s]
Uploading:  47%|████▋     | 4.53M/9.62M [00:02<00:03, 1.74MB/s]
Uploading:  49%|████▉     | 4.72M/9.62M [00:02<00:02, 1.75MB/s]
Uploading:  51%|█████     | 4.92M/9.62M [00:02<00:02, 1.83MB/s]
Uploading:  53%|█████▎    | 5.14M/9.62M [00:02<00:02, 1.92MB/s]
Uploading:  55%|█████▌    | 5.33M/9.62M [00:03<00:02, 1.90MB/s]
Uploading:  57%|█████▋    | 5.52M/9.62M [00:03<00:02, 1.75MB/s]
Uploading:  60%|█████▉    | 5.73M/9.62M [00:03<00:02, 1.70MB/s]
Uploading:  62%|██████▏   | 5.94M/9.62M [00:03<00:02, 1.68MB/s]
Uploading:  64%|██████▍   | 6.16M/9.62M [00:03<00:02, 1.75MB/s]
Uploading:  67%|██████▋   | 6.41M/9.62M [00:03<00:01, 1.96MB/s]
Uploading:  69%|██████▊   | 6.61M/9.62M [00:03<00:01, 1.82MB/s]
Uploading:  71%|███████   | 6.80M/9.62M [00:03<00:01, 1.84MB/s]
Uploading:  73%|███████▎  | 7.00M/9.62M [00:04<00:01, 1.71MB/s]
Uploading:  75%|███████▌  | 7.22M/9.62M [00:04<00:01, 1.71MB/s]
Uploading:  77%|███████▋  | 7.44M/9.62M [00:04<00:01, 1.32MB/s]
Uploading:  80%|███████▉  | 7.69M/9.62M [00:04<00:01, 1.21MB/s]
Uploading:  83%|████████▎ | 7.97M/9.62M [00:04<00:01, 1.47MB/s]
Uploading:  85%|████████▌ | 8.22M/9.62M [00:04<00:00, 1.68MB/s]
Uploading:  88%|████████▊ | 8.48M/9.62M [00:05<00:00, 1.83MB/s]
Uploading:  91%|█████████ | 8.75M/9.62M [00:05<00:00, 1.84MB/s]
Uploading:  94%|█████████▍| 9.03M/9.62M [00:05<00:00, 2.04MB/s]
Uploading:  96%|█████████▋| 9.27M/9.62M [00:05<00:00, 2.13MB/s]
Uploading: 100%|██████████| 9.62M/9.62M [00:06<00:00, 1.67MB/s]
7it [00:47,  6.38s/it]
Uploading:   0%|          | 0.00/10.1M [00:00<?, ?B/s]
Uploading:   7%|▋         | 672k/9.62M [00:00<00:02, 4.69MB/s]
Uploading:  12%|█▏        | 1.11M/9.62M [00:00<00:02, 3.27MB/s]
Uploading:  15%|█▌        | 1.48M/9.62M [00:00<00:02, 3.41MB/s]
Uploading:  19%|█▉        | 1.83M/9.62M [00:00<00:02, 3.19MB/s]
Uploading:  22%|██▏       | 2.14M/9.62M [00:00<00:02, 3.14MB/s]
Uploading:  25%|██▌       | 2.45M/9.62M [00:00<00:02, 3.03MB/s]
Uploading:  29%|██▊       | 2.75M/9.62M [00:00<00:02, 3.01MB/s]
Uploading:  32%|███▏      | 3.05M/9.62M [00:01<00:02, 3.01MB/s]
Uploading:  35%|███▍      | 3.34M/9.62M [00:01<00:02, 2.85MB/s]
Uploading:  38%|███▊      | 3.62M/9.62M [00:01<00:02, 2.87MB/s]
Uploading:  41%|████      | 3.91M/9.62M [00:01<00:02, 2.59MB/s]

In [40]:
# If you have a dem generated you can upload it so we don't need to reprocess.
ingest.upload_dem_to_db(method='agisoft',  # the method used to generate the dem.
                        dem_date='11/25/2024',  # the date the dem was generated.
                        file_name='dem.tif')

Saving to /Volumes/ue1_prod_catalog_119738067017277/tier1_raw/data/tnau-coimbatore/bets/2025:ind:maize:spring/west_field_03/section_b/drone/corn_health_assessment_flight/2024-11-25/dem/agisoft_2024-11-25/dem.tif

Uploading: 100%|██████████| 1.45G/1.45G [13:58<00:00, 1.86MB/s]

In [41]:
# f"{drone_flight_path}/orthomosaic/{method}_{date}/{image_name}"
ingest.upload_orthomosaic_to_db(method='agisoft',  # the method used to generate the ortho.
                                ortho_date='11/25/2024', # the date the ortho was generated.
                                camera='multi-spec', # The camera that was used.
                                file_name='ms.tif')  # if RGB then you can name it rgb.tif

Saving to /Volumes/ue1_prod_catalog_119738067017277/tier1_raw/data/tnau-coimbatore/bets/2025:ind:maize:spring/west_field_03/section_b/drone/corn_health_assessment_flight/2024-11-25/orthomosaic/agisoft_2024-11-25/multi-spec/ms.tif

Uploading: 100%|██████████| 2.00G/2.00G [18:48<00:00, 1.91MB/s]